### ISSUE TITLE
Hmm

### ISSUE THREAD

**Issue by HeyItsMicro** [physuru/i64csc#1]
Hmm
How did I Get here

**Comment by physuru** [comment]
micro you are lost and confused.

**Comment by HeyItsMicro** [comment]
Ohhh 😮 OOPS 😅

**Comment by HeyItsMicro** [comment]
@magnetardev

**Comment by physuru** [comment]
the library is shit why did physuru not do a slab allocation there what a fucking bitch ass pussy hate that guy

**Comment by HeyItsMicro** [comment]
Fr man I would have just used Go (the language @skittyblock)

**Comment by physuru** [comment]
Hi gang i am assembling an e - mail group

**Comment by HeyItsMicro** [comment]
Hi 
 Incriminating 
Micro dev
Xxx

**Comment by physuru** [comment]
breaking the law

**Comment by HeyItsMicro** [comment]
@s0n1cdev

**Comment by physuru** [comment]
with fiddlesticks

**Comment by HeyItsMicro** [comment]
@s0n1c

**Comment by physuru** [comment]
and mean comments

**Comment by HeyItsMicro** [comment]
@itss0n1c

**Comment by physuru** [comment]
micro you are bringing together the entirety of github and for _what_?

**Comment by HeyItsMicro** [comment]
LMFAO
I need to launch an attack on Apple for the iPhone 14 PrO

**Comment by HeyItsMicro** [comment]
Hi please answer my email
 - pal micro

**Comment by physuru** [comment]
aight then
closing issue before you spam anyone else's inbox via i64csc issues
